import json
import os
import random
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from openai import OpenAI

BUILD = Path("build")
API_KEY = os.environ.get("BYNARA_API_KEY", "").strip()
BASE_URL = os.environ.get("BYNARA_BASE_URL", "https://router.bynara.id/v1")
MODEL = os.environ.get("BYNARA_MODEL", "muse-spark-1.2-contributor-free")
GENRE_ENV = os.environ.get("GENRE", "").strip()
CATEGORY_ENV = os.environ.get("CATEGORY", "").strip()

GENRES = [
    "Sci-Fi", "Fantasy", "Mystery", "Horror", "Romance", "Adventure",
    "Comedy", "Thriller", "Fairy Tale", "Slice of Life", "Cyberpunk",
    "Western", "Post-Apocalyptic", "Magical Realism", "Mythology Retelling",
]
CATEGORIES = [
    "Bedtime Story", "Cautionary Tale", "Hero's Journey", "The Heist",
    "Ghost Story", "First Contact", "Lost Love", "Sweet Revenge",
    "Redemption Arc", "Underdog Victory", "Time Loop", "Forbidden Discovery",
    "Unlikely Friendship", "The Last of Its Kind", "A Deal Gone Wrong",
]

SYSTEM = (
    "You are a professional short-form video scriptwriter. You write original, "
    "gripping micro-stories that will be narrated aloud by a calm AI voice over "
    "still artwork. You always respond with valid JSON only. "
    "Do not think step by step. Do not reason or plan silently. "
    "Begin your response with '{' and answer immediately with the JSON object."
)

TEMPLATE = """Write the narration script for a 5-minute "mini movie" vertical reel. This is a mini movie told in 10 scenes across 3 acts.

Genre: {genre}
Category: {category}

Respond with ONLY one valid JSON object, no markdown, no commentary:
{{
  "title": string,
  "logline": string,
  "characters": [{{"name": string, "visual": string}}],
  "world": string,
  "palette": string,
  "scenes": [{{"text": string, "image_prompt": string}}]
}}

STORY STRUCTURE (3 acts, 10 scenes):
- Act 1 (scenes 1-3): Cold-open hook that makes people stop scrolling. Introduce the protagonist and world. Scene 3 ends with the inciting incident.
- Act 2 (scenes 4-7): Escalating stakes. Scene 5 midpoint reversal. Scene 7 is the lowest point / all-is-lost moment.
- Act 3 (scenes 8-10): Climax, resolution, and a final "button" line that pays off the opening scene.

NARRATION RULES:
1. Exactly 10 scenes, each "text" 72-80 words of flowing spoken narration. Short punchy sentences. Concrete sensory details. No scene numbers, no headings, no dialogue tags.
2. Scene 1 opens with a direct-address hook (e.g. "You've never seen a dragon like this.").
3. Scenes 1-9 each END on a mini-cliffhanger or open question that pulls the viewer to the next scene.
4. Scene 10 ends with a satisfying payoff, twist, or haunting final line that calls back to scene 1.
5. Total narration must fit 5 minutes at natural pace (target 740-790 total words).
6. Family-friendly and completely original.

VISUAL BIBLE RULES (critical - images are AI-generated by a weak model):
7. "characters": 1-2 named characters. Each "visual" is a SHORT CONCRETE description of 8-14 words that can be repeated verbatim, e.g. "a small crimson dragon with golden horns and emerald eyes". No personality words, only visible features.
8. "world": 8-14 word concrete description of the main setting, e.g. "a misty pine forest with glowing blue mushrooms and ancient stone ruins".
9. "palette": 3-6 words naming literal colors, e.g. "crimson red, emerald green, midnight blue".
10. Every "image_prompt" must REUSE the exact character "visual" words verbatim and the exact "world" words verbatim, then add ONLY the scene-specific action and framing. Under 35 words total. Structure: "<character visual> <doing scene action> in <world>, <palette>".
11. Image prompts use concrete nouns and actions only. No abstract mood words (no "ethereal", "haunting", "majestic"). No close-up faces, no text, no letters, no watermarks, no multiple unrelated subjects.
12. Each image_prompt must show THE single most important visual moment of its scene - the shot a movie director would choose."""

EXAMPLE = """Example of the exact format (for a different genre - do not copy content):
{{
  "title": "The Lighthouse That Ate Storms",
  "logline": "A lonely keeper's parrot discovers the lighthouse beams are swallowing storms, and must choose between the town's safety and the bird that saved her.",
  "characters": [
    {{"name": "Mara", "visual": "an old lighthouse keeper in a yellow raincoat and gray braided hair"}},
    {{"name": "Peck", "visual": "a white cockatoo with orange crest feathers and black bead eyes"}}
  ],
  "world": "a rocky ocean coast with a tall striped lighthouse under dark storm clouds",
  "palette": "stormy gray, golden yellow, deep navy",
  "scenes": [
    {{"text": "...", "image_prompt": "an old lighthouse keeper in a yellow raincoat and gray braided hair climbing winding stairs in a rocky ocean coast with a tall striped lighthouse under dark storm clouds, stormy gray, golden yellow, deep navy"}}
  ]
}}"""


def extract_json(raw):
    text = (raw or "").strip()
    text = re.sub(r"^```[a-zA-Z]*\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("no JSON object found in response")
    return json.loads(text[start : end + 1])


def validate(data, genre, category):
    if not isinstance(data, dict):
        raise ValueError("response is not a JSON object")
    title = str(data.get("title") or "Untitled Reel").strip()[:120]
    logline = str(data.get("logline") or "").strip()[:300]
    characters_raw = data.get("characters") or []
    characters = []
    if isinstance(characters_raw, list):
        for ch in characters_raw[:3]:
            if isinstance(ch, dict):
                name = str(ch.get("name") or "").strip()[:40]
                visual = " ".join(str(ch.get("visual") or "").split())[:160]
                if name and visual:
                    characters.append({"name": name, "visual": visual})
    world = " ".join(str(data.get("world") or "").split())[:160]
    palette = " ".join(str(data.get("palette") or "").split())[:80]
    scenes_raw = data.get("scenes")
    if not isinstance(scenes_raw, list) or not (10 <= len(scenes_raw) <= 10):
        raise ValueError("need exactly 10 scenes")
    scenes = []
    for i, sc in enumerate(scenes_raw, 1):
        if not isinstance(sc, dict):
            raise ValueError(f"scene {i} is not an object")
        text = " ".join(str(sc.get("text") or "").split())
        image_prompt = " ".join(
            str(sc.get("image_prompt") or sc.get("imagePrompt") or "").split()
        )
        if len(text) < 250:
            raise ValueError(f"scene {i} narration too short ({len(text)} chars, need >= 250)")
        if not image_prompt:
            raise ValueError(f"scene {i} missing image_prompt")
        scenes.append(
            {
                "text": text,
                "image_prompt": image_prompt[:300],
                "word_count": len(text.split()),
            }
        )
    total_words = sum(s["word_count"] for s in scenes)
    if not (680 <= total_words <= 860):
        raise ValueError(f"total words {total_words} outside 680-860 band")
    return {
        "title": title,
        "logline": logline,
        "genre": genre,
        "category": category,
        "characters": characters,
        "world": world,
        "palette": palette,
        "scenes": scenes,
        "total_words": total_words,
    }


def call_llm(client, genre, category):
    response = client.chat.completions.create(
        model=MODEL,
        temperature=0.85,
        max_tokens=6000,
        messages=[
            {"role": "system", "content": SYSTEM},
            {
                "role": "user",
                "content": TEMPLATE.format(genre=genre, category=category)
                + "\n\n"
                + EXAMPLE,
            },
        ],
    )
    return response.choices[0].message.content or ""


def main():
    if not API_KEY:
        sys.exit("BYNARA_API_KEY is not set")
    BUILD.mkdir(parents=True, exist_ok=True)
    genre = GENRE_ENV or random.choice(GENRES)
    category = CATEGORY_ENV or random.choice(CATEGORIES)
    print(f"Selected combo: {genre} / {category}", flush=True)
    client = OpenAI(base_url=BASE_URL, api_key=API_KEY, timeout=240)
    story = None
    last_error = None
    for attempt in range(1, 4):
        try:
            raw = call_llm(client, genre, category)
            story = validate(extract_json(raw), genre, category)
            break
        except Exception as exc:
            last_error = exc
            print(f"attempt {attempt} failed: {exc}", flush=True)
            if attempt < 3:
                time.sleep(5 * attempt)
    if story is None:
        sys.exit(f"story generation failed: {last_error}")
    story["created_at"] = datetime.now(timezone.utc).isoformat()
    story["model"] = MODEL
    story["total_words"] = sum(s["word_count"] for s in story["scenes"])
    (BUILD / "story.json").write_text(
        json.dumps(story, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(
        f"OK: '{story['title']}' - {len(story['scenes'])} scenes, "
        f"{story['total_words']} words, {len(story['characters'])} characters",
        flush=True,
    )
    print(f"world: {story['world']}", flush=True)
    print(f"palette: {story['palette']}", flush=True)


if __name__ == "__main__":
    main()
